include("${CMAKE_CURRENT_LIST_DIR}/GameInputs.cmake")
foreach(input MARATHON_RECOMP_XEX_INPUT MARATHON_RECOMP_shader_INPUT MARATHON_RECOMP_shader_lt_INPUT)
    if(NOT EXISTS "${${input}}" OR IS_DIRECTORY "${${input}}")
        message(FATAL_ERROR "Missing original game input: ${${input}}. See docs/IOS.md.")
    endif()
    file(SIZE "${${input}}" input_size)
    if(input_size EQUAL 0)
        message(FATAL_ERROR "Original game input is empty: ${${input}}")
    endif()
endforeach()
message(STATUS "Original game inputs will be read from ${MARATHON_RECOMP_GAME_INPUT_DIR}")
